// Shape of assets/requirements-graph.json — generated by tools/build_graph.py, read-only.

import type { SimulationLinkDatum, SimulationNodeDatum } from 'd3';

export type GraphLayer = 'source' | 'branch' | 'profile' | 'rule' | 'deliverable';

export type Severity = 'blocker' | 'major' | 'minor';
export type Verification =
  | 'automatic'
  | 'expert_evidence'
  | 'external_fact'
  | 'external_verdict';
export type DeliverableKind = 'form' | 'file' | 'package' | 'external' | 'verdict';
export type LinkKind =
  | 'partOf'
  | 'branch'
  | 'transcribedInto'
  | 'contains'
  | 'dependsOnSource'
  | 'impacts'
  | 'produces'
  | 'submitted';

export interface SourceNode {
  id: string;
  layer: 'source';
  label: string;
  status: string;
  transcribed: 'none' | 'partial' | 'full';
  monitored: boolean;
  url: string;
}

export interface BranchNode {
  id: string;
  layer: 'branch';
  label: string;
  sourceId: string;
  ruleCount: number;
  registry: boolean;
}

export interface ProfileNode {
  id: string;
  layer: 'profile';
  label: string;
  status: 'draft' | 'active';
  ruleCount: number;
}

export interface RuleNode {
  id: string;
  layer: 'rule';
  label: string;
  ruleId: string;
  /** Bare profile slug — NOT a graph node id. Use {@link profileNodeId} to resolve it to one. */
  profileId: string;
  category: string;
  severity: Severity;
  verification: Verification;
  pending: boolean;
  sourceRef: string;
}

export interface DeliverableNode {
  id: string;
  layer: 'deliverable';
  label: string;
  kind: DeliverableKind;
  origin: string;
  fmt: string;
  blockedBy: string | null;
  isOutcome: boolean;
}

export type GraphNode = SourceNode | BranchNode | ProfileNode | RuleNode | DeliverableNode;

export interface GraphLinkRaw {
  source: string;
  target: string;
  kind: LinkKind;
}

export interface RequirementsGraphFile {
  generatedFrom: string;
  note: string;
  counts: Record<GraphLayer, number>;
  nodes: GraphNode[];
  links: GraphLinkRaw[];
}

/** RuleNode.profileId is a bare slug (e.g. "agr-request-package"); profile node ids are prefixed. */
export function profileNodeId(bareProfileId: string): string {
  return `profile:${bareProfileId}`;
}

// d3-force mutates link.source/target from string ids to node objects in place.
export type SimNode = GraphNode & SimulationNodeDatum;

export interface SimLink extends SimulationLinkDatum<SimNode> {
  kind: LinkKind;
}
